INSERT INTO USUARIO (IDENTIFICACION_USUARIO,TIPO_USUARIO) VALUES ('974148',1);
INSERT INTO USUARIO (IDENTIFICACION_USUARIO,TIPO_USUARIO) VALUES ('7481545',2);
INSERT INTO USUARIO (IDENTIFICACION_USUARIO,TIPO_USUARIO) VALUES ('74851254',3);
INSERT INTO USUARIO (IDENTIFICACION_USUARIO,TIPO_USUARIO) VALUES ('1111111111',3);

INSERT INTO LIBRO (ISBN) VALUES ('ASDA7884');
INSERT INTO LIBRO (ISBN) VALUES ('AWQ489');
INSERT INTO LIBRO (ISBN) VALUES ('EQWQW8545');